logging.level.org.springframework.web: INFO

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
  social:
    facebook:
      app-id: dummy
      app-secret: dummy
    google:
      app-id: dummyy
      app-secret: dummy
  http:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  server:
    context-root: /api
datasource:
  primary:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:timeDb"

server.connection-timeout: 5000

embedded-redis: true

email-verification-url: "http://default-environment.gmiyyqg4qr.us-east-2.elasticbeanstalk.com/#/email-verify"
user-invite-url: "http://default-environment.gmiyyqg4qr.us-east-2.elasticbeanstalk.com/#/user-create"
#needs to be on social provider whitelists
social-login-host: "http://default-environment.gmiyyqg4qr.us-east-2.elasticbeanstalk.com/api"
social-redirect-url: "http://default-environment.gmiyyqg4qr.us-east-2.elasticbeanstalk.com/#/social/login"
default-profile-url: "https://s3.us-east-2.amazonaws.com/natetimeappbucket/defaultprofile.svg"

spring.mail:
  host: smtp.gmail.com
  port: 587
  properties.mail.smtp:
    auth: true
    enable: true
    starttls.enable: true

com.amazonaws.services.s3.enableV4: true
S3:
  profile-pic-bucket: natetimeappbucket
  key-id: dummy
  secret: dummy

