logging.level.org.springframework.web: INFO

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
  social:
    facebook:
      app-id: dummy
      app-secret: dummy

datasource:
  primary:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:timeDb"

email-verification-base-url: http://localhost:8090
#needs to be on social provider whitelists
social-login-host: "http://localhost:8090/api"
social-redirect-url: "http://localhost:8090/#/home"

spring.mail:
  host: smtp.gmail.com
  port: 587
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true
