zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8080
    ui:
      path: /**
      url: http://localhost:4200

ribbon.eureka.enabled: false

spring:
  http:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB

server:
  port: 8090
